### PR TITLE
issue#40 毕竟too young

### PR DESCRIPTION
**Pull request by chihz**
#40

### CODE REVIEW

**Comment by chihongze** [comment]
@github-bot-chihz release it

**Comment by chihongze** [comment]
@github-bot-chihz release it

**Comment by github-bot-chihz** [comment]
@chihongze  已经成功创建release-1.4分支，以及新的tag: eldermob-1.4.RC1

**Comment by chihongze** [comment]
@github-bot-chihz deploy RC1 to sandbox with tirift web

**Comment by github-bot-chihz** [comment]
@chihongze  Got it，正在处理，处理详情请您[登录Acolyte查看 ](http://acloyte.io)

**Pull request merged**
